[package]
authors = ["Jeff Muizelaar <jrmuizel@gmail.com>"]
edition = "2018"
name = "cbindgen-macro"
version = "0.1.0"

[dependencies]
proc-macro2 = "0.4.27"
quote = "0.6.11"

[dependencies.syn]
features = ["full"]
version = "0.15.2"

[lib]
proc-macro = true
